apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-text-analyzer
  labels:
    app: ai-text-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-text-analyzer
  template:
    metadata:
      labels:
        app: ai-text-analyzer
    spec:
      containers:
      - name: analyzer
        image: c3gowda/sentiment-analysis:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
