apiVersion: v1
kind: Service
metadata:
  name: ai-text-analyzer-service
spec:
  selector:
    app: ai-text-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
